export enum ChannelName {
  ACTIVE_USER = 'active-user',
  IAM_ACTIVE = 'iam-active',
  USERS_ACTIVE = 'users-active',
  CHANGE_POSITION = 'change-position',
  INVITATIONS = 'invitations',
  ACCEPTED_INVITATION = 'accepted-invitation',
  MESSAGE_FROM_SERVER = 'message-from-server',
  MESSAGE_FROM_CLIENT = 'message-from-client',
  CHANNEL_REMINDER_TIMER = 'channel-reminder-timer',
  CHANNEL_END = 'channel-end',
  SECOND_CHANCE = 'second-chance',
  NOTIFICATION_CONTINUE_CHANNEL = 'notification-continue-channel',
  REJECTED = 'rejected',
  UNREADED_MESSAGE = 'unreaded-message',
  CANCEL_CHAT = 'cancel-chat',
  CANCELED_INVITATION = 'canceled-invitation',
  CHANNELS = 'channels',
  CHECK_SENT_MESSAGE = 'check-sent-message',
  MESSAGE_DELETED = 'message-deleted',
}
