export const USER_REPOSITORY = 'TYPEORM_USER_REPOSITORY';
export const AUTH_REPOSITORY = 'TYPEORM_AUTH_REPOSITORY';
export const USER_ACTIVATION_REPOSITORY = 'TYPEORM_USER_ACTIVATION_REPOSITORY';
export const FILE_REPOSITORY = 'TYPEORM_FILE_REPOSITORY';
export const INVITATION_REPOSITORY = 'TYPEORM_INVITATION_REPOSITORY';
export const CHANNEL_REPOSITORY = 'TYPEORM_CHANNEL_REPOSITORY';
export const CHANNEL_USER_REPOSITORY = 'TYPEORM_CHANNEL_USER_REPOSITORY';
export const MESSAGE_REPOSITORY = 'TYPEORM_MESSAGE_REPOSITORY';
export const MESSAGE_FILE_REPOSITORY = 'TYPEORM_MESSAGE_FILE_REPOSITORY';
export const USER_PHOTO_REPOSITORY = 'TYPEORM_USER_PHOTO_REPOSITORY';

export const EVENT_REPOSITORY = 'TYPEORM_EVENT_REPOSITORY';

export const CITY_REPOSITORY = 'TYPEORM_CITY_REPOSITORY';

export const USER_REPORT_REPOSITORY = 'TYPEORM_USER_REPORT_REPOSITORY';

export const USER_BLOCK_REPOSITORY = 'TYPEORM_USER_BLOCK_REPOSITORY';

export const USER_LIVE_REPOSITORY = 'TYPEORM_USER_BLOCKED_REPOSITORY';

export const COUNTRY_REPOSITORY = 'TYPEORM_COUNTRY_REPOSITORY';

export const FORBIDDEN_WORD_REPOSITORY = 'TYPEORM_FORBIDDEN_WORD_REPOSITORY';

export const EVENT_CATEGORY_REPOSITORY = 'TYPEORM_EVENT_CATEGORY_REPOSITORY';
export const USER_ACTIVE_HISTORY_REPOSITORY =
  'TYPEORM_USER_ACTIVE_HISTORY_REPOSITORY';

export const COMPLAINT_REPOSITORY = 'TYPEORM_COMPLAINT_REPOSITORY';

export const EVENT_BUS = 'EVENT_EMITTER_EVENT_BUS';
export const TYPEORM_ENVIRONMENT_ARRANGER = 'TYPEORM_ENVIRONMENT_ARRANGER';
